name: Daily Build
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Trigger build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Tell healthchecks.io the action has started
        run: curl --max-time 10 --retry 5 -f -sS -L https://hc-ping.com/${{ secrets.healthcheck_id }}/start

      - name: Trigger Netlify build hook
        run: curl -X POST -f -sS -L https://api.netlify.com/build_hooks/${{ secrets.build_hook_id }}
        if: ${{ always() }} # still run the build if the healthcheck curl fails!

      - name: Tell healthchecks.io if the action succeeded
        run: curl --max-time 10 --retry 5 -f -sS -L https://hc-ping.com/${{ secrets.healthcheck_id }}

      - name: Tell healthchecks.io if the action failed
        run: curl --max-time 10 --retry 5 -f -sS -L https://hc-ping.com/${{ secrets.healthcheck_id }}/fail
        if: ${{ failure() }}
