name: Update Dependencies
on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby but not gems
        uses: ruby/setup-ruby@v1
      - name: Update dependencies
        run: |
          echo 'BUNDLER_OUTPUT<<UPDATE_EOF' >> $GITHUB_ENV
          bundle update | tee -a $GITHUB_ENV
          echo >> $GITHUB_ENV
          echo 'UPDATE_EOF' >> $GITHUB_ENV
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: "Gemfile*"
          commit-message: "Update dependencies"
          branch: create-pull-request/update-dependencies
          title: Update dependencies
          body: |
            Automated dependency update. Bundler output:

            ```
            ${{ env.BUNDLER_OUTPUT }}
            ```
